apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
stringData:
  DB_USER: "tech-challenge-fase"
  DB_PASSWORD: "tech-challenge-fase"
  DB_URI: "postgres://tech-challenge-fase:tech-challenge-fase@postgres/tech-challenge-fase?sslmode=disable"
